version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: donorwalletdb
      POSTGRES_USER: donorwalletuser
      POSTGRES_PASSWORD: donorwalletpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
